-- Seed 90 predefined dates
-- NOTE: Titles #36, #79 are OCR-recovered from the PDF and flagged for manual review.
--       #36 "Vestir iguales" was between "Armar un LEGO" and "Disfraz en pareja" in the PDF.
--       #79 "Ir a un acuario" — PDF page 79 had no visible title; this is a best guess.
--       #37/#47 resolved: "Disfraz en pareja" at #37, "Pijamada" at #47 (no duplicates).
INSERT INTO dates (title, category, order_index) VALUES
  ('Cenar en un restaurante bonito', 'predefined', 1),
  ('Viaje fuera de la ciudad', 'predefined', 2),
  ('Pedir cena a domicilio', 'predefined', 3),
  ('Armar un rompecabezas', 'predefined', 4),
  ('Preparar un postre', 'predefined', 5),
  ('Pintar un cuadro', 'predefined', 6),
  ('Ir a patinar', 'predefined', 7),
  ('Hacer galletas', 'predefined', 8),
  ('Maratón de series o películas', 'predefined', 9),
  ('Ir a un museo', 'predefined', 10),
  ('Ir a un mirador', 'predefined', 11),
  ('Ir a un zoológico', 'predefined', 12),
  ('Ir de compras', 'predefined', 13),
  ('Ir a remar', 'predefined', 14),
  ('Ir a un circo', 'predefined', 15),
  ('Ir a una fiesta', 'predefined', 16),
  ('Ir a un nacimiento navideño', 'predefined', 17),
  ('Ir por un helado', 'predefined', 18),
  ('Ir a un cumpleaños', 'predefined', 19),
  ('Ir a un baby shower', 'predefined', 20),
  ('Ir a una boda', 'predefined', 21),
  ('Ir a una cascada', 'predefined', 22),
  ('Ir a pedir (actividad sorpresa)', 'predefined', 23),
  ('Pasear en lancha', 'predefined', 24),
  ('Ir a acampar', 'predefined', 25),
  ('Caminar bajo la lluvia', 'predefined', 26),
  ('Amanecer juntos', 'predefined', 27),
  ('Ver una película', 'predefined', 28),
  ('Desayunar juntos', 'predefined', 29),
  ('Ver una serie completa', 'predefined', 30),
  ('Hacer una obra de arte', 'predefined', 31),
  ('Pintar una pared', 'predefined', 32),
  ('Dibujar algo', 'predefined', 33),
  ('Cultivar una planta', 'predefined', 34),
  ('Armar un LEGO', 'predefined', 35),
  ('Vestir iguales', 'predefined', 36),
  ('Disfraz en pareja', 'predefined', 37),
  ('Jugar un videojuego', 'predefined', 38),
  ('Estudiar juntos', 'predefined', 39),
  ('Hacer una limpieza facial', 'predefined', 40),
  ('Bailar', 'predefined', 41),
  ('Ver un documental', 'predefined', 42),
  ('Escuchar música', 'predefined', 43),
  ('Armar un mueble', 'predefined', 44),
  ('Volar un papalote', 'predefined', 45),
  ('Guerra de almohadas', 'predefined', 46),
  ('Pijamada', 'predefined', 47),
  ('Observar las estrellas', 'predefined', 48),
  ('Hacer una cita con temática', 'predefined', 49),
  ('Pasear a nuestras mascotas', 'predefined', 50),
  ('Salir a caminar', 'predefined', 51),
  ('Hacer una fogata', 'predefined', 52),
  ('Hacer una sesión de fotos', 'predefined', 53),
  ('Hacer una manualidad', 'predefined', 54),
  ('Jugar un juego de mesa', 'predefined', 55),
  ('Escribir un deseo en un globo', 'predefined', 56),
  ('Comer donas', 'predefined', 57),
  ('Pedir pizza', 'predefined', 58),
  ('Ir a un buffet', 'predefined', 59),
  ('Hacer una caja de ahorro', 'predefined', 60),
  ('Ver la luna', 'predefined', 61),
  ('Hacer una carta', 'predefined', 62),
  ('Hacernos un tatuaje', 'predefined', 63),
  ('Ir a un pueblito mágico', 'predefined', 64),
  ('Ir a un SPA', 'predefined', 65),
  ('Cena familiar', 'predefined', 66),
  ('Ir por hamburguesas', 'predefined', 67),
  ('Un paseo familiar', 'predefined', 68),
  ('Salir con amigos', 'predefined', 69),
  ('Hacer hot cakes', 'predefined', 70),
  ('Cenar tacos', 'predefined', 71),
  ('Ir a Six Flags', 'predefined', 72),
  ('Sacar un peluche de una máquina', 'predefined', 73),
  ('Ir a un parque acuático', 'predefined', 74),
  ('Ir a jugar bolos', 'predefined', 75),
  ('Guerra de globos', 'predefined', 76),
  ('Paseo nocturno en bicicleta', 'predefined', 77),
  ('Ir a un planetario', 'predefined', 78),
  ('Ir a un acuario', 'predefined', 79),
  ('Ir a una obra de teatro', 'predefined', 80),
  ('Cena romántica en casa', 'predefined', 81),
  ('Cocinar juntos', 'predefined', 82),
  ('Ir al cine', 'predefined', 83),
  ('Hacer un picnic', 'predefined', 84),
  ('Visitar un mercado', 'predefined', 85),
  ('Ir a un concierto', 'predefined', 86),
  ('Tomar un taller juntos', 'predefined', 87),
  ('Hacer voluntariado juntos', 'predefined', 88),
  ('Ir a un festival', 'predefined', 89),
  ('Crear un álbum de recuerdos', 'predefined', 90);

-- Seed 10 free dates (title is NULL, user fills in later)
INSERT INTO dates (title, category, order_index) VALUES
  (NULL, 'free', 91),
  (NULL, 'free', 92),
  (NULL, 'free', 93),
  (NULL, 'free', 94),
  (NULL, 'free', 95),
  (NULL, 'free', 96),
  (NULL, 'free', 97),
  (NULL, 'free', 98),
  (NULL, 'free', 99),
  (NULL, 'free', 100);
